### ISSUE TITLE
SP PRO Fans, QL Fans and Hydro X reported as CCDT_Invalid

### ISSUE THREAD

**Issue by Legion2** [CorsairOfficial/cue-sdk#1]
When selecting SP PRO Fan, QL Fan or Hydro X in the Lighting setup of a LNP in iCUE, the cue-sdk report `CCDT_Invalid` as `CorsairChannelDeviceType` when calling `CorsairGetDeviceInfo`.

**Comment by intrueder** [comment]
I confirm, 
the issue can be reproduced with iCUE v3.25.60 + CUE SDK v3.0.301

**Comment by intrueder** [comment]
There is a new `CorsairChannelDeviceType` member called `CCDT_QL_Fan` in [CUE SDK v3.0.355](https://github.com/CorsairOfficial/cue-sdk/releases/tag/v3.0.355)

**Comment by intrueder** [comment]
Completely fixed in [CUE SDK v3.0.361](https://github.com/CorsairOfficial/cue-sdk/releases/tag/v3.0.361)
