### ISSUE TITLE
Any plans for VS2019 and C# examples?

### ISSUE THREAD

**Issue by SimonFearby** [CorsairOfficial/cue-sdk#15]
Error opening examples in VS2019

C:\Projects\iCueSDK\cue-sdk-master\cue-sdk-master\src\examples\properties_example\properties_example\properties_example.vcxproj : warning  : The build tools for v141 cannot be found. Install v141 to build using the v141 build tools.

C:\Projects\iCueSDK\cue-sdk-master\cue-sdk-master\src\examples\properties_example\properties_example\properties_example.vcxproj : warning  : Platform 'Win32' referenced in the project file 'properties_example' cannot be found.

C:\Projects\iCueSDK\cue-sdk-master\cue-sdk-master\src\examples\properties_example\properties_example\properties_example.vcxproj : warning  : Platform 'x64' referenced in the project file 'properties_example' cannot be found.

error : Designtime build failed for project 'C:\Projects\iCueSDK\cue-sdk-master\cue-sdk-master\src\examples\properties_example\properties_example\properties_example.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
error : Designtime build failed for project 'C:\Projects\iCueSDK\cue-sdk-master\cue-sdk-master\src\examples\properties_example\properties_example\properties_example.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
error : Designtime build failed for project 'C:\Projects\iCueSDK\cue-sdk-master\cue-sdk-master\src\examples\properties_example\properties_example\properties_example.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
error : Designtime build failed for project 'C:\Projects\iCueSDK\cue-sdk-master\cue-sdk-master\src\examples\properties_example\properties_example\properties_example.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
error : Designtime build failed for project 'C:\Projects\iCueSDK\cue-sdk-master\cue-sdk-master\src\examples\properties_example\properties_example\properties_example.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
error : Designtime build failed for project 'C:\Projects\iCueSDK\cue-sdk-master\cue-sdk-master\src\examples\properties_example\properties_example\properties_example.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
error : Designtime build failed for project 'C:\Projects\iCueSDK\cue-sdk-master\cue-sdk-master\src\examples\properties_example\properties_example\properties_example.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
error : Designtime build failed for project 'C:\Projects\iCueSDK\cue-sdk-master\cue-sdk-master\src\examples\properties_example\properties_example\properties_example.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
error : Designtime build failed for project 'C:\Projects\iCueSDK\cue-sdk-master\cue-sdk-master\src\examples\properties_example\properties_example\properties_example.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.
error : Designtime build failed for project 'C:\Projects\iCueSDK\cue-sdk-master\cue-sdk-master\src\examples\properties_example\properties_example\properties_example.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.

**Comment by intrueder** [comment]
This repository is for C version of CUESDK, and it is not a good place for C# examples.
Also, I don't think it would be a good idea to provide examples for all versions of VisualStudio, as porting examples to VS2019 shouldn't be very difficult.
You should check project properties, and update build tools version there.

**Comment by AndrewBabbitt97** [comment]
FYI: I maintain a C# version of CUESDK here: https://github.com/RGBKit/CUESDK.NET

You can also find it on NuGet, the calls are 1:1

**Comment by xoblite** [comment]
Possibly off-topic since you're asking for C# examples, but I maintain a C/C++ based plugin for my shell project here:
[https://github.com/xoblite/xoblite-plugins/tree/main/xControlRGB-Corsair](https://github.com/xoblite/xoblite-plugins/tree/main/xControlRGB-Corsair)

BR//Karl aka qwilk/@xoblite
