### ISSUE TITLE
K100 Support

### ISSUE THREAD

**Issue by Rartii** [CorsairOfficial/cue-sdk#25]
The Corsair K100 lacks proper support, it is not on the supported devices list and some LEDs can not be controlled by SDK.
The green LEDs can, the red LEDs can not be controlled by SDK.
![K100](https://user-images.githubusercontent.com/47690543/116388971-b5f1b780-a81c-11eb-9e74-9510c3928c34.png)

**Comment by intrueder** [comment]
What versions of SDK and iCUE do you have?

**Comment by Rartii** [comment]
It's 4.10.273.

**Comment by intrueder** [comment]
OK, what software do you use to control the K100 LEDs?

**Comment by Rartii** [comment]
I have tried Aurora, Artemis and Terraria. All of those programs were unable to change those additional leds. It could be very likely that those programs use older version of SDK. But the keyboard is not on the supported device list so I am not sure.

**Comment by DarthAffe** [comment]
As aurora and Artemis are both using RGB.NET for corsair support I checked this and already found why the LED-bar LEDs aren't working (I somehow missed that there're new ones) https://github.com/DarthAffe/RGB.NET/issues/210
But I'm not sure about the logo and the left key (not sure what it is), still need to check them.

**Comment by intrueder** [comment]
Hi @DarthAffe , thanks for the reply.
Here is a list of unmapped K100 LEDs:
CLK_Profile - switch profile key
CLI_Oem1 - CLI_Oem3 - logo
CLI_Oem4 - CLI_Oem12 - dial key + ring LEDs
CLKLP_Zone20 - CLKLP_Zone45 - the rest of Lightbar LEDs

**Comment by intrueder** [comment]
FYI, K100 RGB is on the [supported devices](https://corsairofficial.github.io/cue-sdk/#supported-devices) list now
