### ISSUE TITLE
Support for K60 RGB PRO keyboards

### ISSUE THREAD

**Issue by xoblite** [CorsairOfficial/cue-sdk#27]
See subject - [support for K60 RGB PRO keyboards](https://github.com/CorsairOfficial/cue-sdk/issues/21) still [seems to be missing](https://corsairofficial.github.io/cue-sdk/#supported-devices) as of late December 2021 (? and/or iCUE maybe doesn't like having more than one keyboard connected at the same time?).

BR//Karl aka qwilk/@xoblite

**Comment by intrueder** [comment]
Hey, @xoblite , thanks for opening this issue. Yes, K60 RGB PRO is still not on the list of supported devices, but despite this it is fully supported in the iCUE. I will update the docs with the next SDK update.

> and/or iCUE maybe doesn't like having more than one keyboard connected at the same time?
It is OK for iCUE to have more than one keyboard connected at the same time.

**Comment by intrueder** [comment]
Fixed in [v3.0.460](https://github.com/CorsairOfficial/cue-sdk/releases/tag/v3.0.460)
