### ISSUE TITLE
K55 keyboard reported as having 3 LED zones, but not controllable (yet?)

### ISSUE THREAD

**Issue by xoblite** [CorsairOfficial/cue-sdk#3]
Hi Corsair & Co,

I'm aware that the **K55 keyboard** (latest firmware v30.08) is not (yet?) a supported device according to [https://corsairofficial.github.io/cue-sdk/#supported-devices](https://corsairofficial.github.io/cue-sdk/#supported-devices), but using the latest CUE SDK v3.0.301 (+ the latest iCUE version 3.25.60, running on Windows 10), **it is reported as having 3 LEDs (i.e. zones) available, even though it's not yet controllable** (or rather, you can send it the regular colour setting commands etc, but nothing happens when you do so). Would love to see the SDK support also entry level devices like these though - any LED is better than no LED after all! :)

Thanks for making the SDK available; keep up the good work!

BR//KHH (@xoblite)

**Comment by intrueder** [comment]
Fixed in iCUE v3.27.68

**Comment by xoblite** [comment]
I can confirm, thanks @intrueder !

BR//KHH (@xoblite )

**Comment by xoblite** [comment]
Sidenote: Coincidentally, this also seems to fix a similar problem with the **HARPOON RGB mouse**, which was previously non-controllable and reported as having 0 LEDs. Pending some further testing, it then seems these two devices can be added to the list of supported devices in the CUE SDK documentation. Thanks!

BR//KHH (@xoblite )
