### ISSUE TITLE
M800(C) not properly released on exit?

### ISSUE THREAD

**Issue by xoblite** [CorsairOfficial/cue-sdk#4]
Hi Corsair & Co,

I have noticed the following issues controlling the **M800(C) mouse pad** (latest firmware v1.02.50) using the latest **CUE SDK v3.0.301** (CUESDK_2013.dll) + the latest iCUE version 3.25.60, running on Windows 10:

- The **M800(C) does not seem to be properly released - or the control returned properly back to iCUE - upon exit of the controlling [shared access mode] SDK client application** like my other devices; **all its LEDs turn static red**. This is also reflected visually in the iCUE application, where you also can not control the device's lighting effects when it is in this state. However, launching the SDK client application again (which then performs a handshake with the SDK etc on startup) works fine.
- **Other devices, like my M65 RGB Elite mouse, do not seem to suffer from the same issue.** This said, I have yet to investigate this further, but thought I'd post it here in the meanwhile in case someone else can confirm this being an issue. If further explanation or testing is needed, please do not hesitate to ask.

Thanks for making the SDK available; keep up the good work!

BR//KHH (@xoblite)

**Comment by xoblite** [comment]
Minor update: After upgrading to the latest **iCUE version 3.26.95**, the behaviour is the same as described above, but now all the LEDs **turn off** (instead of turning static red) upon exit. [Full disclosure: I have not rebooted my computer since upgrading iCUE - it didn't ask for me to either though - if that is of any relevance at all here.]

**Comment by intrueder** [comment]
Hi @xoblite ,
I checked on the same configuration and everything works as expected.
Do you have any effect configured for the mouse pad under the "Lighting Effects" tab in iCUE?

**Comment by xoblite** [comment]
Hi @intrueder ,

yes, of course. This said, I have also performed some additional testing since my last post, and **it turns out I don't even have to start/exit my SDK client for this to happen; I just need to launch the iCUE SW directly after boot-up** (yes, I've tried rebooting etc multiple times of course) and the same "lock-up" occurs that I described above. In fact, launching my SDK client application brings it _out_ of this state... ...and then when I exit my application it returns to the previous "locked" state. So, perhaps we shouldn't be looking at this from the SDK end of things after all, but rather from the iCUE end of things? (nb. I obviously have zero knowledge of its inner workings though so I can only speculate here). And again, as far as I can tell this issue is isolated to the M800(C). Any thoughts?

_PS. Even though already the latest version, I've also tried force updating the firmware on my M800C; no luck there._

**Comment by intrueder** [comment]
@xoblite ,
I'm not sure, but it looks like some other application using the SDK is installed on your system.
Can you go to iCUE settings and uncheck "Enable SDK" option and see what happens after launching the iCUE directly after boot-up?

**Comment by xoblite** [comment]
Disabled the SDK in iCUE and rebooted, still the same. Well actually, this time around I waited a while longer before launching iCUE, and it turns out the M800C locked up even _prior_ to i.e. without launching iCUE (of course, with the SDK currently disabled I can't do any further testing that I'm aware of). Again, my other devices are not affected; only the M800C.

**Comment by intrueder** [comment]
@xoblite I'd recommend you to create a post about this problem on the [Corsair User Forums](https://forum.corsair.com/), and don't forget to include the hardware configuration.

Thank you for your research! 👌

Closing this as not related to CUESDK.

**Comment by xoblite** [comment]
Thanks @intrueder , I have now created a post on the Corsair User Forums (which by the way are archaic to say the least but hopefully well monitored by the iCUE folks) linking to this issue:
[https://forum.corsair.com/v3/showthread.php?t=194717](https://forum.corsair.com/v3/showthread.php?t=194717)

BR//KHH (@xoblite)

**Comment by xoblite** [comment]
For information only: This issue remains in iCUE v3.27.68.

BR//KHH (@xoblite)

**Comment by xoblite** [comment]
For information only: This issue remains in iCUE v3.28.70.

BR//KHH (@xoblite)

**Comment by xoblite** [comment]
For information only: This issue remains in iCUE v3.29.110.
...and the regular Corsair forum is a [dead end](https://forum.corsair.com/v3/showthread.php?t=194717) support-wise. Please advice.

BR//KHH (@xoblite)

**Comment by intrueder** [comment]
@xoblite , waiting for more information on the Corsair forum
