### ISSUE TITLE
Vengeance RGB Pro Not Working

### ISSUE THREAD

**Issue by smerkousdavid** [CorsairOfficial/cue-sdk#6]
It appears to me that the vengeance rgb pro is not working on my machine. I've setup a simple controller for all of my corsair devices, (keyboard, pump, ram, mouse). Everything seems to work just fine, full control, with `CorsairSetLedsColorsBufferByDeviceIndex` and `CorsairSetLedsColorsFlushBufferAsync`, except for the Vengeance RGB Pro as nothing happens to the device.

When using `CorsairGetDeviceInfo` and `CorsairGetLedPositionsByDeviceIndex` it seems like the modules and the leds have been detected just fine for all of the devices including Vengeance. I see valid leds from CLDRAM_1 -> CLDRAM_10 (600 -> 609) for that device index.

I've also tried the not recommended way of excluding the "device index" function variant. Is there anything special I need to do for the Vengeance?

**Comment by intrueder** [comment]
Hi @smerkousdavid!
In iCUE, go to device settings and ensure that "Enable full software control" option is checked for the Vengeance RGB Pro

**Comment by smerkousdavid** [comment]
Thank you so much @intrueder . I feel kinda stupid that the solution to my problem was just a simple check. Everything seems to work now.
