### ISSUE TITLE
k57: No Lightning from 3rd party in wireless mode

### ISSUE THREAD

**Issue by UniCizin** [CorsairOfficial/cue-sdk#8]
Hey guys,

i am using the k57 (mostly in wireless mode).
For the lightning, i use the Software [Aurora](http://www.project-aurora.com/)
This works fine. I can pass Razer game effects etc to my keyboard via the icue-sdk.
BUT ONLY when i attach the cable. 

As soon as i go wireless, the lightning stops. And i'm pretty sure its not the a 3rd-Party error, because the preview of my keyboard in icue is still getting lightning updates, but the actual keyboard does not.

for clarification: the attached screenshot shows both the aurora and icue with the correct lightning, the keyboard itself stays black.

![icueAurora](https://user-images.githubusercontent.com/41308043/79638901-6fd53300-8188-11ea-99ef-8952427edf94.png)

(PS: i am not on the most recent version of icue, because these versions dont find my keyboard at all. but thats another issue i guess)

**Comment by intrueder** [comment]
Unfortunately, devices in wireless mode are not supported by SDK

**Comment by UniCizin** [comment]
thats sad, because i bought this keyboard because it is wireless AND has
RGB lightning, but the lightning is only 50% usable with this restriction :(
is there a plan to activate this in the future?

Am Di., 21. Apr. 2020 um 12:52 Uhr schrieb Tymur Mudzhyri <
notifications@github.com>:

**Comment by intrueder** [comment]
As people started to refer to this issue, I need to be more specific: direct lighting (software lighting being set using SDK) for **keyboards** in wireless mode is not supported

**Comment by NicTanghe** [comment]
Does annyone have anny idea how to put pressure on corsair to support this functionality ?
